echo "this is my first jenkins demo project"
echo "naresh is a devops engineer"
echo "this system host name is : `hostname`"
echo "jenkins workspace dir is `pwd`"
echo "hai"
echo "hi naresh"
echo "how are you ?"
